Reanme ./src/ to ./rubber/ and move rubber scripts to bin/
This allows to execute ./bin/rubber directly from the local
checkout/workspace. The only requirement is to run "python3 setup.py
build" first, to generate verison.py.

Instead of

$ ./rubber
raceback (most recent call last):
  File "./rubber", line 4, in <module>
    import rubber.cmdline
ModuleNotFoundError: No module named 'rubber'

users can now

$ python3 setup.py build

and then run ./bin/rubber directly. Without any installation step.